[[custom_groups]]
name = "AUTO"
type = "url-test"
rule = ["^(?!niovpn-)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "PROXY"
type = "select"
rule = ["[]AUTO", "^(?!niovpn-)"]

[[custom_groups]]
name = "NIOVPN"
type = "select"
rule = ["^niovpn"]
